# Generated by Django 3.2.7 on 2021-09-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_auto_20210911_1720'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='primary_hospital',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='primary_physician',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.doctor'),
        ),
    ]
