# Generated by Django 3.2.7 on 2021-09-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20210911_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='primary_hospital',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='primary_physician',
        ),
    ]
